name: MADS KRABBE FOTOGRAFI
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: MADS KRABBE FOTOGRAFI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10121d'
    - '#989993'
    - '#6e6e6c'
    - '#bdbcb7'
    - '#aa8478'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.875
  rhythmicContrast: 0
purpose: []
