name: MADS KRABBE FOTOGRAFI
favicon: null
layout_spectrum: 0.1713802085723728
typography_spectrum: 0.5378924501128495
title: MADS KRABBE FOTOGRAFI
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#10121d'
    - '#989993'
    - '#6e6e6c'
    - '#bdbcb7'
    - '#aa8478'
  brandStrength: 0.867401238065213
  lightness: 0.17069773515686393
  saturation: 0.1654707370325923
  rhythmicContrast: 0.613459792919457
purpose: []
